version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4173:4173"
    environment:
      CF_API_TOKEN: ${CF_API_TOKEN}
      AUTH_BCRYPT_HASH: ${AUTH_BCRYPT_HASH}
      SESSION_SECRET: ${SESSION_SECRET}
      CF_API_BASE: ${CF_API_BASE:-https://api.cloudflare.com/client/v4}
    restart: unless-stopped
